import type { Dashboard } from "@hiveswarm/contracts";

const now = new Date();
const minutesAgo = (minutes: number) => new Date(now.getTime() - minutes * 60_000).toISOString();

export function createDemoDashboard(): Dashboard {
  return {
    engagement: {
      id: "eng_demo",
      name: "Northstar portal",
      target: "app.northstar.test",
      status: "running",
      startedAt: minutesAgo(18),
      scopeRules: [
        { id: "scope_1", kind: "domain", value: "*.northstar.test", action: "allow" },
        { id: "scope_2", kind: "host", value: "admin.northstar.test", action: "deny" },
      ],
    },
    metrics: { activeAgents: 4, assets: 18, findings: 4, pendingApprovals: 1 },
    agents: [
      {
        id: "ar_orchestrator",
        runId: "run_demo",
        parentAgentRunId: null,
        agentId: "orchestrator",
        agentName: "Orchestrator",
        lifecycle: "session",
        status: "running",
        depth: 0,
        task: "Coordinate the authorized evaluation and synthesize evidence.",
        target: "app.northstar.test",
        requestedCapabilities: [],
        executionPlan: [],
        startedAt: minutesAgo(18),
        completedAt: null,
        logCount: 27,
      },
      {
        id: "ar_explorer",
        runId: "run_demo",
        parentAgentRunId: "ar_orchestrator",
        agentId: "explorer",
        agentName: "Explorer",
        lifecycle: "session",
        status: "waiting_approval",
        depth: 1,
        task: "Map reachable application surfaces and propose scope changes.",
        target: "app.northstar.test",
        requestedCapabilities: ["network.passive", "browser.interactive", "scope.propose", "graph.write"],
        executionPlan: [],
        startedAt: minutesAgo(16),
        completedAt: null,
        logCount: 14,
      },
      {
        id: "ar_browser",
        runId: "run_demo",
        parentAgentRunId: "ar_explorer",
        agentId: "browser-user",
        agentName: "Browser user",
        lifecycle: "session",
        status: "running",
        depth: 2,
        task: "Exercise the sign-in and workspace invitation flows.",
        target: "https://app.northstar.test",
        requestedCapabilities: ["network.passive", "browser.interactive", "graph.write", "finding.write"],
        executionPlan: [],
        startedAt: minutesAgo(12),
        completedAt: null,
        logCount: 19,
      },
      {
        id: "ar_source",
        runId: "run_demo",
        parentAgentRunId: "ar_orchestrator",
        agentId: "source-review",
        agentName: "Source review",
        lifecycle: "task",
        status: "running",
        depth: 1,
        task: "Review authorization boundaries in the invitation workflow.",
        target: "repository:northstar/web",
        requestedCapabilities: ["source.read", "graph.write", "finding.write"],
        executionPlan: [],
        startedAt: minutesAgo(9),
        completedAt: null,
        logCount: 11,
      },
      {
        id: "ar_ports",
        runId: "run_demo",
        parentAgentRunId: "ar_explorer",
        agentId: "port-scanner",
        agentName: "Port scanner",
        lifecycle: "task",
        status: "completed",
        depth: 2,
        task: "Identify services on the authorized application host.",
        target: "app.northstar.test",
        requestedCapabilities: ["network.active", "graph.write"],
        executionPlan: [],
        startedAt: minutesAgo(14),
        completedAt: minutesAgo(11),
        logCount: 8,
      },
    ],
    findings: [
      {
        id: "finding_1",
        title: "Invitation token remains valid after role change",
        severity: "high",
        status: "confirmed",
        confidence: 0.94,
        assetLabel: "/api/invitations/accept",
        summary: "A previously issued invitation can retain elevated workspace membership after the inviter reduces the intended role.",
        evidence: ["Request pair captured in the authorized test tenant", "Role transition reproduced twice"],
        remediation: "Bind acceptance to the current invitation record and invalidate the previous token when its role changes.",
        discoveredBy: "Source review",
        createdAt: minutesAgo(5),
      },
      {
        id: "finding_2",
        title: "Verbose GraphQL schema exposed",
        severity: "medium",
        status: "open",
        confidence: 0.86,
        assetLabel: "/graphql",
        summary: "Schema introspection reveals internal mutation names in the production-like test environment.",
        evidence: ["Introspection query returned 214 types"],
        remediation: "Restrict introspection in production and review field-level authorization independently.",
        discoveredBy: "Browser user",
        createdAt: minutesAgo(8),
      },
      {
        id: "finding_3",
        title: "Administrative route disclosed in client bundle",
        severity: "low",
        status: "open",
        confidence: 0.78,
        assetLabel: "/assets/app.js",
        summary: "The client route manifest references a separate administrative hostname that is outside the current scope.",
        evidence: ["Bundle string: admin.northstar.test"],
        discoveredBy: "Explorer",
        createdAt: minutesAgo(10),
      },
      {
        id: "finding_4",
        title: "Security headers are consistently configured",
        severity: "info",
        status: "confirmed",
        confidence: 0.99,
        assetLabel: "app.northstar.test",
        summary: "HSTS, frame restrictions, and MIME sniffing protections are present on sampled routes.",
        evidence: ["12 responses sampled"],
        discoveredBy: "Browser user",
        createdAt: minutesAgo(7),
      },
    ],
    approvals: [
      {
        id: "approval_1",
        runId: "run_demo",
        agentRunId: "ar_explorer",
        type: "scope_expansion",
        status: "pending",
        title: "Review administrative host",
        rationale: "The client bundle references an administrative control plane that may share the invitation API.",
        requestedAction: "Add admin.northstar.test to the allowlist for passive browser exploration only.",
        requestedBy: "Explorer",
        createdAt: minutesAgo(4),
        context: { kind: "scope_proposal", scopeKind: "host", scopeValue: "admin.northstar.test" },
      },
    ],
    graph: {
      nodes: [
        { id: "node_app", kind: "website", label: "app.northstar.test", subtitle: "Primary target", status: "active", metadata: {}, discoveredBy: "Orchestrator", createdAt: minutesAgo(18) },
        { id: "node_443", kind: "service", label: "HTTPS :443", subtitle: "nginx 1.26", status: "reachable", metadata: {}, discoveredBy: "Port scanner", createdAt: minutesAgo(12) },
        { id: "node_login", kind: "endpoint", label: "/login", subtitle: "GET · 200", status: "observed", metadata: {}, discoveredBy: "Browser user", createdAt: minutesAgo(11) },
        { id: "node_graphql", kind: "endpoint", label: "/graphql", subtitle: "POST · 200", severity: "medium", status: "finding", metadata: {}, discoveredBy: "Browser user", createdAt: minutesAgo(9) },
        { id: "node_invite", kind: "endpoint", label: "/api/invitations/accept", subtitle: "POST · authorization path", severity: "high", status: "finding", metadata: {}, discoveredBy: "Source review", createdAt: minutesAgo(6) },
        { id: "node_repo", kind: "repository", label: "northstar/web", subtitle: "main · 8f31c2a", status: "reviewing", metadata: {}, discoveredBy: "Orchestrator", createdAt: minutesAgo(10) },
        { id: "node_admin", kind: "subdomain", label: "admin.northstar.test", subtitle: "Outside current scope", status: "scope-review", metadata: {}, discoveredBy: "Explorer", createdAt: minutesAgo(5) },
        { id: "node_finding", kind: "finding", label: "Stale invitation token", subtitle: "High severity", severity: "high", status: "confirmed", metadata: { findingId: "finding_1" }, discoveredBy: "Source review", createdAt: minutesAgo(5) },
      ],
      edges: [
        { id: "edge_1", source: "node_app", target: "node_443", relationship: "exposes", metadata: {} },
        { id: "edge_2", source: "node_app", target: "node_login", relationship: "serves", metadata: {} },
        { id: "edge_3", source: "node_app", target: "node_graphql", relationship: "serves", metadata: {} },
        { id: "edge_4", source: "node_graphql", target: "node_invite", relationship: "calls", metadata: {} },
        { id: "edge_5", source: "node_repo", target: "node_invite", relationship: "implements", metadata: {} },
        { id: "edge_6", source: "node_invite", target: "node_finding", relationship: "affected_by", metadata: {} },
        { id: "edge_7", source: "node_app", target: "node_admin", relationship: "references", metadata: {} },
      ],
    },
    logs: [
      { id: "log_1", agentRunId: "ar_explorer", level: "info", message: "Route inventory complete: 17 first-party paths", timestamp: minutesAgo(6) },
      { id: "log_2", agentRunId: "ar_source", level: "info", message: "Tracing invitation role checks across controller and service", timestamp: minutesAgo(5) },
      { id: "log_3", agentRunId: "ar_browser", level: "warn", message: "GraphQL introspection is enabled on the target", timestamp: minutesAgo(5) },
      { id: "log_4", agentRunId: "ar_explorer", level: "warn", message: "Scope boundary reached: admin.northstar.test", timestamp: minutesAgo(4) },
      { id: "log_5", agentRunId: "ar_source", level: "info", message: "Reporter received structured evidence for finding_1", timestamp: minutesAgo(3) },
    ],
    artifacts: [],
  };
}
